### ISSUE TITLE
2.8.5 release notes appear to be missing from pivnet

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/pcf-release-notes#281]
Hi there, just a heads up, despite the merge [here a few days ago](https://github.com/pivotal-cf/pcf-release-notes/commit/135da96d2beed8cd92aa9e7d9073bcdcc6b614f1), it appears 2.8.5 release notes are not visible on pivnet (https://docs.pivotal.io/platform/2-8/release-notes/runtime-rn.html)

just giving a heads up 👍 thanks

**Comment by seviet** [comment]
Thank you so much @aegershman! Looks like the prod job just wasn't pushed -- pushed it and now they're live. I think we've granted RelEng the right to push to prod, however let me know if that's not the case? Otherwise, def recommend pinging #pcf-docs to do the push if you have a release that needs to go out.

https://docs.pivotal.io/platform/2-8/release-notes/runtime-rn.html#2.8.5
