### ISSUE TITLE
Bug not listed in know Issue section

### ISSUE THREAD

**Issue by avannala-pivotal** [pivotal-cf/pcf-release-notes#87]
This bug is not listed in know issues section https://www.pivotaltracker.com/n/projects/555129/stories/157602876.

**Comment by pspinrad** [comment]
Closing -- per Zendesk https://discuss.zendesk.com/agent/tickets/83362 this was fixed in patches:
1.12 - https://www.pivotaltracker.com/n/projects/975916/stories/157677095
2.0 - https://www.pivotaltracker.com/n/projects/975916/stories/157677020
2.1 - https://www.pivotaltracker.com/n/projects/975916/stories/157676938
